package movies

import (
	"database/sql"
	"os"
	"path/filepath"
	"testing"

	_ "modernc.org/sqlite"
)

// openTestDB creates a temporary SQLite database with the movies schema applied.
func openTestDB(t *testing.T) *sql.DB {
	t.Helper()
	dir := t.TempDir()
	db, err := sql.Open("sqlite", filepath.Join(dir, "movies_test.db"))
	if err != nil {
		t.Fatalf("open test db: %v", err)
	}
	if _, err := db.Exec(moviesSchema); err != nil {
		t.Fatalf("create schema: %v", err)
	}
	t.Cleanup(func() { _ = db.Close() })
	return db
}

// ── insertMovie ───────────────────────────────────────────────────────────────

// mustInsert inserts a movie and fatals on error — for use in test setup.
func mustInsert(t *testing.T, db *sql.DB, m movie) int64 {
	t.Helper()
	id, err := insertMovie(db, m)
	if err != nil {
		t.Fatalf("insertMovie: %v", err)
	}
	return id
}

func TestInsertMovie_Basic(t *testing.T) {
	db := openTestDB(t)
	m := movie{Title: "Alien", Year: 1979}
	id, err := insertMovie(db, m)
	if err != nil {
		t.Fatalf("insertMovie: %v", err)
	}
	if id <= 0 {
		t.Errorf("expected positive id, got %d", id)
	}
}

func TestInsertMovie_UUIDAutoGenerated(t *testing.T) {
	db := openTestDB(t)
	id, _ := insertMovie(db, movie{Title: "Alien", Year: 1979})
	got, err := getMovie(db, id)
	if err != nil {
		t.Fatalf("getMovie: %v", err)
	}
	if got.UUID == "" {
		t.Error("UUID should be auto-generated, got empty string")
	}
}

func TestInsertMovie_WithTagsAndActors(t *testing.T) {
	db := openTestDB(t)
	m := movie{
		Title: "Alien",
		Year:  1979,
		Tags:  []string{"horror", "sci-fi"},
		Actors: []movieActor{
			{Name: "Sigourney Weaver", Role: "Ripley", SortOrder: 0},
			{Name: "Tom Skerritt", Role: "Dallas", SortOrder: 1},
		},
	}
	id, err := insertMovie(db, m)
	if err != nil {
		t.Fatalf("insertMovie: %v", err)
	}

	got, err := getMovie(db, id)
	if err != nil {
		t.Fatalf("getMovie: %v", err)
	}

	if len(got.Tags) != 2 {
		t.Errorf("expected 2 tags, got %d: %v", len(got.Tags), got.Tags)
	}
	if len(got.Actors) != 2 {
		t.Errorf("expected 2 actors, got %d", len(got.Actors))
	}
	if got.Actors[0].Name != "Sigourney Weaver" {
		t.Errorf("unexpected first actor: %s", got.Actors[0].Name)
	}
}

func TestInsertMovie_DuplicateUUIDError(t *testing.T) {
	db := openTestDB(t)
	uid := "test-uuid-1234"
	_, err := insertMovie(db, movie{Title: "A", UUID: uid})
	if err != nil {
		t.Fatalf("first insert: %v", err)
	}
	_, err = insertMovie(db, movie{Title: "B", UUID: uid})
	if err == nil {
		t.Error("expected error for duplicate UUID, got nil")
	}
}

// ── updateMovie ───────────────────────────────────────────────────────────────

func TestUpdateMovie_Fields(t *testing.T) {
	db := openTestDB(t)
	id, _ := insertMovie(db, movie{Title: "Old Title", Year: 2000, Tags: []string{"action"}})

	updated := movie{
		ID:    id,
		Title: "New Title",
		Year:  2001,
		Tags:  []string{"drama"},
	}
	if err := updateMovie(db, updated); err != nil {
		t.Fatalf("updateMovie: %v", err)
	}

	got, _ := getMovie(db, id)
	if got.Title != "New Title" {
		t.Errorf("title: want %q, got %q", "New Title", got.Title)
	}
	if got.Year != 2001 {
		t.Errorf("year: want 2001, got %d", got.Year)
	}
	if len(got.Tags) != 1 || got.Tags[0] != "drama" {
		t.Errorf("tags not replaced: %v", got.Tags)
	}
}

func TestUpdateMovie_ReplacesActors(t *testing.T) {
	db := openTestDB(t)
	id, _ := insertMovie(db, movie{
		Title:  "Movie",
		Actors: []movieActor{{Name: "Actor A", SortOrder: 0}},
	})

	_ = updateMovie(db, movie{
		ID:     id,
		Title:  "Movie",
		Actors: []movieActor{{Name: "Actor B", SortOrder: 0}},
	})

	got, _ := getMovie(db, id)
	if len(got.Actors) != 1 || got.Actors[0].Name != "Actor B" {
		t.Errorf("actors not replaced: %v", got.Actors)
	}
}

// ── deleteMovie ───────────────────────────────────────────────────────────────

func TestDeleteMovie_RemovesRow(t *testing.T) {
	db := openTestDB(t)
	id, _ := insertMovie(db, movie{Title: "To Delete"})
	if err := deleteMovie(db, id); err != nil {
		t.Fatalf("deleteMovie: %v", err)
	}
	_, err := getMovie(db, id)
	if err == nil {
		t.Error("expected error after delete, got nil")
	}
}

func TestDeleteMovie_CascadesToTagsAndActors(t *testing.T) {
	db := openTestDB(t)
	id, _ := insertMovie(db, movie{
		Title:  "Cascade Test",
		Tags:   []string{"horror"},
		Actors: []movieActor{{Name: "Someone", SortOrder: 0}},
	})
	_ = deleteMovie(db, id)

	var tagCount, actorCount int
	if err := db.QueryRow(`SELECT COUNT(*) FROM movie_tags WHERE movie_id=?`, id).Scan(&tagCount); err != nil {
		t.Fatalf("scan tag count: %v", err)
	}
	if err := db.QueryRow(`SELECT COUNT(*) FROM movie_actors WHERE movie_id=?`, id).Scan(&actorCount); err != nil {
		t.Fatalf("scan actor count: %v", err)
	}

	if tagCount != 0 {
		t.Errorf("expected 0 tags after delete, got %d", tagCount)
	}
	if actorCount != 0 {
		t.Errorf("expected 0 actors after delete, got %d", actorCount)
	}
}

// ── getMovieByUUID ────────────────────────────────────────────────────────────

func TestGetMovieByUUID(t *testing.T) {
	db := openTestDB(t)
	id, _ := insertMovie(db, movie{Title: "UUID Test", Year: 1999})
	byID, _ := getMovie(db, id)

	byUUID, err := getMovieByUUID(db, byID.UUID)
	if err != nil {
		t.Fatalf("getMovieByUUID: %v", err)
	}
	if byUUID.ID != id {
		t.Errorf("id mismatch: want %d, got %d", id, byUUID.ID)
	}
}

func TestGetMovieByUUID_NotFound(t *testing.T) {
	db := openTestDB(t)
	_, err := getMovieByUUID(db, "no-such-uuid")
	if err == nil {
		t.Error("expected error for missing UUID")
	}
}

// ── updateMoviePoster ─────────────────────────────────────────────────────────

func TestUpdateMoviePoster(t *testing.T) {
	db := openTestDB(t)
	id, _ := insertMovie(db, movie{Title: "Poster Test", PosterURL: "/old/path.jpg"})
	if err := updateMoviePoster(db, id, "/new/path.jpg"); err != nil {
		t.Fatalf("updateMoviePoster: %v", err)
	}
	got, _ := getMovie(db, id)
	if got.PosterURL != "/new/path.jpg" {
		t.Errorf("poster_url: want %q, got %q", "/new/path.jpg", got.PosterURL)
	}
}

// ── listMovies – filtering ─────────────────────────────────────────────────────

func TestListMovies_All(t *testing.T) {
	db := openTestDB(t)
	mustInsert(t, db, movie{Title: "Alpha"})
	mustInsert(t, db, movie{Title: "Beta"})

	movies, err := listMovies(db, "", "", "", "title", false)
	if err != nil {
		t.Fatalf("listMovies: %v", err)
	}
	if len(movies) != 2 {
		t.Errorf("expected 2 movies, got %d", len(movies))
	}
}

func TestListMovies_FilterByTag(t *testing.T) {
	db := openTestDB(t)
	mustInsert(t, db, movie{Title: "Horror Film", Tags: []string{"horror"}})
	mustInsert(t, db, movie{Title: "Comedy", Tags: []string{"comedy"}})

	results, _ := listMovies(db, "horror", "", "", "title", false)
	if len(results) != 1 || results[0].Title != "Horror Film" {
		t.Errorf("tag filter failed: %v", results)
	}
}

func TestListMovies_FilterBySetName(t *testing.T) {
	db := openTestDB(t)
	mustInsert(t, db, movie{Title: "Movie 1", SetName: "Bond Collection"})
	mustInsert(t, db, movie{Title: "Movie 2", SetName: "Bond Collection"})
	mustInsert(t, db, movie{Title: "Standalone"})

	results, _ := listMovies(db, "", "", "Bond Collection", "title", false)
	if len(results) != 2 {
		t.Errorf("set filter: expected 2, got %d", len(results))
	}
}

func TestListMovies_SearchTitle(t *testing.T) {
	db := openTestDB(t)
	mustInsert(t, db, movie{Title: "Terminator 2", Plot: "Robot action"})
	mustInsert(t, db, movie{Title: "Alien", Plot: "Space terminator"})

	results, _ := listMovies(db, "", "Terminator", "", "title", false)
	if len(results) != 1 || results[0].Title != "Terminator 2" {
		t.Errorf("title search: %v", results)
	}
}

func TestListMovies_SearchFulltext(t *testing.T) {
	db := openTestDB(t)
	mustInsert(t, db, movie{Title: "Alien", Plot: "Space horror"})
	mustInsert(t, db, movie{Title: "Comedy", Plot: "Funny stuff"})

	results, _ := listMovies(db, "", "horror", "", "title", true)
	if len(results) != 1 || results[0].Title != "Alien" {
		t.Errorf("fulltext search: %v", results)
	}
}

func TestListMovies_SearchTitleOnlyNotMatchPlot(t *testing.T) {
	db := openTestDB(t)
	mustInsert(t, db, movie{Title: "Comedy", Plot: "A horror film"})

	results, _ := listMovies(db, "", "horror", "", "title", false)
	if len(results) != 0 {
		t.Errorf("title-only search should not match plot, got %d results", len(results))
	}
}

// ── listMovies – sort order ────────────────────────────────────────────────────

func TestListMovies_SortByTitle_IgnoresThe(t *testing.T) {
	db := openTestDB(t)
	mustInsert(t, db, movie{Title: "The Mummy", Year: 1999})
	mustInsert(t, db, movie{Title: "Alien", Year: 1979})
	mustInsert(t, db, movie{Title: "Batman", Year: 1989})

	results, _ := listMovies(db, "", "", "", "title", false)
	titles := make([]string, len(results))
	for i, m := range results {
		titles[i] = m.Title
	}
	// "The Mummy" should sort as "Mummy" → between Batman and... after Batman
	want := []string{"Alien", "Batman", "The Mummy"}
	for i, w := range want {
		if i >= len(titles) || titles[i] != w {
			t.Errorf("sort by title: want %v, got %v", want, titles)
			break
		}
	}
}

func TestListMovies_SortByYear(t *testing.T) {
	db := openTestDB(t)
	mustInsert(t, db, movie{Title: "C", Year: 2000})
	mustInsert(t, db, movie{Title: "A", Year: 1980})
	mustInsert(t, db, movie{Title: "B", Year: 1990})

	results, _ := listMovies(db, "", "", "", "year", false)
	if results[0].Year != 1980 || results[1].Year != 1990 || results[2].Year != 2000 {
		t.Errorf("sort by year failed: %v", results)
	}
}

func TestListMovies_SortByRuntime(t *testing.T) {
	db := openTestDB(t)
	mustInsert(t, db, movie{Title: "Long", Runtime: 180})
	mustInsert(t, db, movie{Title: "Short", Runtime: 90})
	mustInsert(t, db, movie{Title: "Medium", Runtime: 120})

	results, _ := listMovies(db, "", "", "", "runtime", false)
	if results[0].Runtime != 90 || results[2].Runtime != 180 {
		t.Errorf("sort by runtime failed: %v", results)
	}
}

func TestListMovies_SortByLastPlayed_MostRecentFirst(t *testing.T) {
	db := openTestDB(t)
	mustInsert(t, db, movie{Title: "Old", LastPlayed: "2022-01-01"})
	mustInsert(t, db, movie{Title: "New", LastPlayed: "2026-01-01"})
	mustInsert(t, db, movie{Title: "Unwatched", LastPlayed: ""})

	results, _ := listMovies(db, "", "", "", "last", false)
	if results[0].Title != "New" {
		t.Errorf("most recent should be first, got %s", results[0].Title)
	}
	if results[len(results)-1].Title != "Unwatched" {
		t.Errorf("unwatched should be last, got %s", results[len(results)-1].Title)
	}
}

func TestListMovies_SortByTitle_UsesSortTitleWhenSet(t *testing.T) {
	db := openTestDB(t)
	// sort_title "dr. no" → sorts under D; "casino royale" → sorts under C
	mustInsert(t, db, movie{Title: "007: Dr. No", SortTitle: "dr. no"})
	mustInsert(t, db, movie{Title: "Casino Royale"})

	results, _ := listMovies(db, "", "", "", "title", false)
	// Casino Royale (c) should come before Dr. No (d)
	if results[0].Title != "Casino Royale" {
		t.Errorf("sort_title not respected: expected Casino Royale first, got %v", results[0].Title)
	}
	if results[1].Title != "007: Dr. No" {
		t.Errorf("expected 007: Dr. No second, got %v", results[1].Title)
	}
}

// ── listMoviesByActor ─────────────────────────────────────────────────────────

func TestListMoviesByActor(t *testing.T) {
	db := openTestDB(t)
	mustInsert(t, db, movie{
		Title:  "Alien",
		Actors: []movieActor{{Name: "Sigourney Weaver", SortOrder: 0}},
	})
	mustInsert(t, db, movie{
		Title:  "Avatar",
		Actors: []movieActor{{Name: "Sigourney Weaver", SortOrder: 0}},
	})
	mustInsert(t, db, movie{
		Title:  "Batman",
		Actors: []movieActor{{Name: "Michael Keaton", SortOrder: 0}},
	})

	results, err := listMoviesByActor(db, "Sigourney Weaver", "title")
	if err != nil {
		t.Fatalf("listMoviesByActor: %v", err)
	}
	if len(results) != 2 {
		t.Errorf("expected 2 movies, got %d", len(results))
	}
}

func TestListMoviesByActor_CaseInsensitive(t *testing.T) {
	db := openTestDB(t)
	mustInsert(t, db, movie{
		Title:  "Aliens",
		Actors: []movieActor{{Name: "Sigourney Weaver", SortOrder: 0}},
	})

	results, _ := listMoviesByActor(db, "sigourney weaver", "title")
	if len(results) != 1 {
		t.Errorf("case-insensitive actor match failed: got %d results", len(results))
	}
}

// ── getTagCounts ──────────────────────────────────────────────────────────────

func TestGetTagCounts_Basic(t *testing.T) {
	db := openTestDB(t)
	mustInsert(t, db, movie{Title: "A", Tags: []string{"horror", "sci-fi"}})
	mustInsert(t, db, movie{Title: "B", Tags: []string{"horror"}})
	mustInsert(t, db, movie{Title: "C", Tags: []string{"comedy"}})

	result, err := getTagCounts(db, "", false)
	if err != nil {
		t.Fatalf("getTagCounts: %v", err)
	}

	total, _ := result["total"].(int)
	if total != 3 {
		t.Errorf("total: want 3, got %d", total)
	}

	counts, _ := result["counts"].([]map[string]any)
	if len(counts) != 3 {
		t.Errorf("expected 3 tags, got %d", len(counts))
	}
	// horror should be first (2 movies)
	if counts[0]["tag"] != "horror" {
		t.Errorf("horror should be most common, got %v", counts[0]["tag"])
	}
}

func TestGetTagCounts_WithSearch(t *testing.T) {
	db := openTestDB(t)
	mustInsert(t, db, movie{Title: "Alien", Tags: []string{"sci-fi"}})
	mustInsert(t, db, movie{Title: "Comedy", Tags: []string{"comedy"}})

	result, _ := getTagCounts(db, "Alien", false)
	total, _ := result["total"].(int)
	if total != 1 {
		t.Errorf("search filter: want total 1, got %d", total)
	}
}

func TestGetTagCounts_EmptyDB(t *testing.T) {
	db := openTestDB(t)
	result, err := getTagCounts(db, "", false)
	if err != nil {
		t.Fatalf("getTagCounts on empty db: %v", err)
	}
	counts, _ := result["counts"].([]map[string]any)
	if len(counts) != 0 {
		t.Errorf("expected empty counts, got %v", counts)
	}
}

// ── setMovieTags ──────────────────────────────────────────────────────────────

func TestSetMovieTags_ReplaceExisting(t *testing.T) {
	db := openTestDB(t)
	id, _ := insertMovie(db, movie{Title: "M", Tags: []string{"a", "b"}})
	if err := setMovieTags(db, id, []string{"c"}); err != nil {
		t.Fatalf("setMovieTags: %v", err)
	}
	tags, _ := getMovieTags(db, id)
	if len(tags) != 1 || tags[0] != "c" {
		t.Errorf("tags not replaced: %v", tags)
	}
}

func TestSetMovieTags_SkipsBlank(t *testing.T) {
	db := openTestDB(t)
	id, _ := insertMovie(db, movie{Title: "M"})
	_ = setMovieTags(db, id, []string{"  ", "action", ""})
	tags, _ := getMovieTags(db, id)
	if len(tags) != 1 || tags[0] != "action" {
		t.Errorf("blank tags not skipped: %v", tags)
	}
}

func TestSetMovieTags_DeduplicatesViaIgnore(t *testing.T) {
	db := openTestDB(t)
	id, _ := insertMovie(db, movie{Title: "M"})
	// INSERT OR IGNORE prevents duplicates
	_ = setMovieTags(db, id, []string{"horror", "horror"})
	tags, _ := getMovieTags(db, id)
	if len(tags) != 1 {
		t.Errorf("duplicates not handled: %v", tags)
	}
}

// ── sortClause ────────────────────────────────────────────────────────────────

func TestSortClause_Default(t *testing.T) {
	got := sortClause("title")
	if got == "" {
		t.Error("sortClause('title') returned empty string")
	}
}

func TestSortClause_UnknownKeyFallsToTitle(t *testing.T) {
	if sortClause("garbage") == "" {
		t.Error("sortClause('garbage') should return title clause")
	}
}

func TestSortClause_AllKnownKeys(t *testing.T) {
	for _, k := range []string{"title", "year", "runtime", "last"} {
		if got := sortClause(k); got == "" {
			t.Errorf("sortClause(%q) returned empty string", k)
		}
	}
}

// ── trimSpace ─────────────────────────────────────────────────────────────────

func TestTrimSpace(t *testing.T) {
	cases := []struct{ in, want string }{
		{"hello", "hello"},
		{"  hello  ", "hello"},
		{"hello   world", "hello world"},
		{"\thello\n", "hello"},
		{"", ""},
		{"   ", ""},
	}
	for _, c := range cases {
		if got := trimSpace(c.in); got != c.want {
			t.Errorf("trimSpace(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

// ── migrateMoviesSchema ───────────────────────────────────────────────────────

func TestMigrateMoviesSchema_Idempotent(t *testing.T) {
	db := openTestDB(t)
	// Running migration twice should not error (columns already exist).
	if err := migrateMoviesSchema(db); err != nil {
		t.Fatalf("first migration: %v", err)
	}
	if err := migrateMoviesSchema(db); err != nil {
		t.Fatalf("second migration: %v", err)
	}
}

// ── isDuplicateColumnError ────────────────────────────────────────────────────

func TestIsDuplicateColumnError(t *testing.T) {
	db := openTestDB(t)
	// Actually trigger a real duplicate column error.
	_, err := db.Exec(`ALTER TABLE movies ADD COLUMN title TEXT`)
	if !isDuplicateColumnError(err) {
		t.Errorf("expected duplicate column error, got: %v", err)
	}
}

func TestIsDuplicateColumnError_Nil(t *testing.T) {
	if isDuplicateColumnError(nil) {
		t.Error("nil error should not be a duplicate column error")
	}
}

// ── file system helpers ───────────────────────────────────────────────────────

func TestTempDirCleanup(t *testing.T) {
	// Verifies t.TempDir() integration — just a sanity check.
	dir := t.TempDir()
	if _, err := os.Stat(dir); err != nil {
		t.Fatalf("temp dir not created: %v", err)
	}
}
