package links

import (
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"keyop/core"
	"keyop/x/search"
)

// Service manages saved links with SQLite storage and favicon caching.
type Service struct {
	Deps   core.Dependencies
	Cfg    core.ServiceConfig
	dbPath string
}

// NewService creates a new links service.
func NewService(deps core.Dependencies, cfg core.ServiceConfig) *Service {
	return &Service{
		Deps:   deps,
		Cfg:    cfg,
		dbPath: "~/.keyop/links/links.sqlite3",
	}
}

// Check performs a health check.
func (svc *Service) Check() error {
	return nil
}

// ValidateConfig validates the service configuration.
func (svc *Service) ValidateConfig() []error {
	// Links service has minimal configuration requirements
	return nil
}

// Initialize initializes the links service.
func (svc *Service) Initialize() error {
	// Lazy-initialize: DB will be opened on first use
	// Just ensure the directory structure exists
	return nil
}

// RegisterRoutes registers custom HTTP routes for image upload and favicon serving.
func (svc *Service) RegisterRoutes(mux *http.ServeMux) {
	mux.HandleFunc("POST /api/links/upload-icon", svc.handleIconUpload)
	mux.HandleFunc("GET /api/links/icon/{path...}", svc.handleServeIcon)
	mux.HandleFunc("GET /api/links/favicon/{id}", svc.handleServeFavicon)
}

// handleIconUpload handles file uploads for custom icons.
func (svc *Service) handleIconUpload(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	// Parse multipart form with 5MB limit
	if err := r.ParseMultipartForm(5 * 1024 * 1024); err != nil {
		http.Error(w, "Failed to parse form", http.StatusBadRequest)
		return
	}

	file, handler, err := r.FormFile("icon")
	if err != nil {
		http.Error(w, "No file provided", http.StatusBadRequest)
		return
	}
	defer func() {
		_ = file.Close()
	}()

	// Validate file extension
	ext := strings.ToLower(filepath.Ext(handler.Filename))
	validExts := map[string]bool{
		".ico":  true,
		".png":  true,
		".jpg":  true,
		".jpeg": true,
		".gif":  true,
	}
	if !validExts[ext] {
		http.Error(w, "Invalid file type. Allowed: .ico, .png, .jpg, .jpeg, .gif", http.StatusBadRequest)
		return
	}

	// Generate unique filename based on timestamp
	dataDir := svc.getDataDir()
	iconsDir := filepath.Join(dataDir, "icons")
	// #nosec G703 - iconsDir is derived from svc.getDataDir() (safe, not user-controlled)
	if err := os.MkdirAll(iconsDir, 0o750); err != nil {
		http.Error(w, "Failed to create icons directory", http.StatusInternalServerError)
		return
	}

	// Save file with timestamp-based filename
	filename := fmt.Sprintf("icon_%d%s", time.Now().UnixNano(), ext)
	filePath := filepath.Join(iconsDir, filename)

	// #nosec G304,G703 - filePath is derived from the icons directory and a computed filename (safe)
	out, err := os.Create(filePath)
	if err != nil {
		http.Error(w, "Failed to save file", http.StatusInternalServerError)
		return
	}
	defer func() {
		_ = out.Close()
	}()

	if _, err := io.Copy(out, file); err != nil {
		http.Error(w, "Failed to write file", http.StatusInternalServerError)
		return
	}

	// Return the relative path for storage in the database
	w.Header().Set("Content-Type", "application/json")
	// #nosec G705 - filename is generated by fmt.Sprintf, not user input
	if _, err := fmt.Fprintf(w, `{"path":"%s"}`, filepath.Join("icons", filename)); err != nil {
		_ = err // error writing to client is not critical
	}
}

// handleServeIcon serves uploaded icon files.
func (svc *Service) handleServeIcon(w http.ResponseWriter, r *http.Request) {
	pathParam := r.PathValue("path")
	if pathParam == "" {
		http.NotFound(w, r)
		return
	}

	// Ensure the path is relative to dataDir and starts with "icons/"
	if !strings.HasPrefix(pathParam, "icons/") {
		http.Error(w, "Invalid path", http.StatusBadRequest)
		return
	}

	// Determine the allowed base directory
	dataDir := svc.getDataDir()
	iconsDir := filepath.Join(dataDir, "icons")

	// Construct and resolve the file path
	filePath := filepath.Join(dataDir, pathParam)
	absIconsDir, errBase := filepath.Abs(iconsDir)
	absFilePath, errFile := filepath.Abs(filePath)

	if errBase != nil || errFile != nil {
		http.Error(w, "Invalid path", http.StatusBadRequest)
		return
	}

	// Ensure the file path is within the icons directory
	if !strings.HasPrefix(absFilePath, absIconsDir+string(filepath.Separator)) && absFilePath != absIconsDir {
		http.Error(w, "Invalid path", http.StatusBadRequest)
		return
	}

	// Serve the file
	http.ServeFile(w, r, filePath)
}

// handleServeFavicon serves a cached favicon by link ID.
func (svc *Service) handleServeFavicon(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	if id == "" {
		http.Error(w, "invalid link id", http.StatusBadRequest)
		return
	}

	link, err := getLink(svc.dbPath, id)
	if err != nil {
		http.Error(w, "link not found", http.StatusNotFound)
		return
	}

	if link.FaviconPath == "" {
		http.Error(w, "no favicon", http.StatusNotFound)
		return
	}

	dataDir := svc.getDataDir()
	var faviconPath string

	// Check if it's a custom icon (starts with "icons/") or a fetched favicon
	if strings.HasPrefix(link.FaviconPath, "icons/") {
		faviconPath = filepath.Join(dataDir, link.FaviconPath)
	} else {
		faviconPath = filepath.Join(dataDir, "favicons", link.FaviconPath)
	}

	// Prevent directory traversal
	absPath, err := filepath.Abs(faviconPath)
	if err != nil {
		http.Error(w, "forbidden", http.StatusForbidden)
		return
	}

	expectedBase, _ := filepath.Abs(dataDir)
	if !strings.HasPrefix(absPath, expectedBase) {
		http.Error(w, "forbidden", http.StatusForbidden)
		return
	}

	// #nosec G703 - path is validated by filepath.Abs and HasPrefix check above
	if _, err := os.Stat(absPath); err != nil {
		http.Error(w, "not found", http.StatusNotFound)
		return
	}

	// Set appropriate content-type
	if strings.HasSuffix(absPath, ".svg") {
		w.Header().Set("Content-Type", "image/svg+xml")
	} else if strings.HasSuffix(absPath, ".png") {
		w.Header().Set("Content-Type", "image/png")
	} else if strings.HasSuffix(absPath, ".jpg") || strings.HasSuffix(absPath, ".jpeg") {
		w.Header().Set("Content-Type", "image/jpeg")
	} else if strings.HasSuffix(absPath, ".gif") {
		w.Header().Set("Content-Type", "image/gif")
	} else if strings.HasSuffix(absPath, ".webp") {
		w.Header().Set("Content-Type", "image/webp")
	} else {
		w.Header().Set("Content-Type", "image/x-icon")
	}

	http.ServeFile(w, r, absPath)
}

// getDataDir returns the data directory for this service.
func (svc *Service) getDataDir() string {
	os := svc.Deps.MustGetOsProvider()
	home, err := os.UserHomeDir()
	if err != nil {
		home = "."
	}
	return filepath.Join(home, ".keyop", "links")
}

// SearchSourceType implements search.IndexProvider.
func (svc *Service) SearchSourceType() string {
	return "links"
}

// BulkIndex implements search.IndexProvider.
func (svc *Service) BulkIndex() (<-chan search.SearchableDocument, error) {
	ch := make(chan search.SearchableDocument)
	go func() {
		defer close(ch)

		logger := svc.Deps.MustGetLogger()
		logger.Info("links BulkIndex started", "dbPath", svc.dbPath)

		db, err := openLinksDB(svc.dbPath)
		if err != nil {
			logger.Error("links BulkIndex: failed to open DB", "error", err)
			return
		}
		defer func() {
			_ = db.Close()
		}()

		rows, err := db.Query(`
			SELECT id, url, domain, name, notes, tags, created_at, updated_at 
			FROM links 
			ORDER BY updated_at DESC
		`)
		if err != nil {
			logger.Error("links BulkIndex: query failed", "error", err)
			return
		}
		defer func() {
			_ = rows.Close()
		}()

		docCount := 0
		for rows.Next() {
			var id string
			var url, domain, name, notes, tags, createdAt, updatedAt string
			if err := rows.Scan(&id, &url, &domain, &name, &notes, &tags, &createdAt, &updatedAt); err != nil {
				logger.Error("links BulkIndex: scan error", "error", err)
				continue
			}

			// Parse tags from comma-separated string
			var tagList []string
			if tags != "" {
				for _, tag := range strings.Split(tags, ",") {
					if t := strings.TrimSpace(tag); t != "" {
						tagList = append(tagList, t)
					}
				}
			}

			// Use name if available, otherwise domain
			title := name
			if title == "" {
				title = domain
			}

			// Build body from notes and URL
			body := notes
			if body == "" {
				body = url
			}

			// Parse updated_at timestamp
			updatedTime, err := time.Parse(time.RFC3339, updatedAt)
			if err != nil {
				updatedTime = time.Now()
			}

			doc := search.SearchableDocument{
				ID:         fmt.Sprintf("links:%s", id),
				SourceType: "links",
				SourceID:   id,
				Title:      title,
				Body:       body,
				Tags:       tagList,
				URL:        url,
				UpdatedAt:  updatedTime,
			}

			logger.Info("links BulkIndex: creating document", "id", doc.ID, "title", doc.Title, "body_len", len(doc.Body), "sourceType", doc.SourceType)

			ch <- doc
			docCount++
		}
		logger.Info("links BulkIndex completed", "documents_indexed", docCount)
	}()
	return ch, nil
}
