package links

import (
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"keyop/core"
)

// Service manages saved links with SQLite storage and favicon caching.
type Service struct {
	Deps   core.Dependencies
	Cfg    core.ServiceConfig
	dbPath string
}

// NewService creates a new links service.
func NewService(deps core.Dependencies, cfg core.ServiceConfig) *Service {
	return &Service{
		Deps:   deps,
		Cfg:    cfg,
		dbPath: "~/.keyop/links/links.sqlite3",
	}
}

// Check performs a health check.
func (svc *Service) Check() error {
	return nil
}

// ValidateConfig validates the service configuration.
func (svc *Service) ValidateConfig() []error {
	// Links service has minimal configuration requirements
	return nil
}

// Initialize initializes the links service.
func (svc *Service) Initialize() error {
	// Lazy-initialize: DB will be opened on first use
	// Just ensure the directory structure exists
	return nil
}

// RegisterRoutes registers custom HTTP routes for image upload and favicon serving.
func (svc *Service) RegisterRoutes(mux *http.ServeMux) {
	mux.HandleFunc("POST /api/links/upload-icon", svc.handleIconUpload)
	mux.HandleFunc("GET /api/links/icon/{path...}", svc.handleServeIcon)
	mux.HandleFunc("GET /api/links/favicon/{id}", svc.handleServeFavicon)
}

// handleIconUpload handles file uploads for custom icons.
func (svc *Service) handleIconUpload(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	// Parse multipart form with 5MB limit
	if err := r.ParseMultipartForm(5 * 1024 * 1024); err != nil {
		http.Error(w, "Failed to parse form", http.StatusBadRequest)
		return
	}

	file, handler, err := r.FormFile("icon")
	if err != nil {
		http.Error(w, "No file provided", http.StatusBadRequest)
		return
	}
	defer func() {
		_ = file.Close()
	}()

	// Validate file extension
	ext := strings.ToLower(filepath.Ext(handler.Filename))
	validExts := map[string]bool{
		".ico":  true,
		".png":  true,
		".jpg":  true,
		".jpeg": true,
		".gif":  true,
	}
	if !validExts[ext] {
		http.Error(w, "Invalid file type. Allowed: .ico, .png, .jpg, .jpeg, .gif", http.StatusBadRequest)
		return
	}

	// Generate unique filename based on timestamp
	dataDir := svc.getDataDir()
	iconsDir := filepath.Join(dataDir, "icons")
	// #nosec G703 - iconsDir is derived from svc.getDataDir() (safe, not user-controlled)
	if err := os.MkdirAll(iconsDir, 0o750); err != nil {
		http.Error(w, "Failed to create icons directory", http.StatusInternalServerError)
		return
	}

	// Save file with timestamp-based filename
	filename := fmt.Sprintf("icon_%d%s", time.Now().UnixNano(), ext)
	filePath := filepath.Join(iconsDir, filename)

	// #nosec G304,G703 - filePath is derived from the icons directory and a computed filename (safe)
	out, err := os.Create(filePath)
	if err != nil {
		http.Error(w, "Failed to save file", http.StatusInternalServerError)
		return
	}
	defer func() {
		_ = out.Close()
	}()

	if _, err := io.Copy(out, file); err != nil {
		http.Error(w, "Failed to write file", http.StatusInternalServerError)
		return
	}

	// Return the relative path for storage in the database
	w.Header().Set("Content-Type", "application/json")
	// #nosec G705 - filename is generated by fmt.Sprintf, not user input
	if _, err := fmt.Fprintf(w, `{"path":"%s"}`, filepath.Join("icons", filename)); err != nil {
		_ = err // error writing to client is not critical
	}
}

// handleServeIcon serves uploaded icon files.
func (svc *Service) handleServeIcon(w http.ResponseWriter, r *http.Request) {
	pathParam := r.PathValue("path")
	if pathParam == "" {
		http.NotFound(w, r)
		return
	}

	// Ensure the path is relative to dataDir and starts with "icons/"
	if !strings.HasPrefix(pathParam, "icons/") {
		http.Error(w, "Invalid path", http.StatusBadRequest)
		return
	}

	// Determine the allowed base directory
	dataDir := svc.getDataDir()
	iconsDir := filepath.Join(dataDir, "icons")

	// Construct and resolve the file path
	filePath := filepath.Join(dataDir, pathParam)
	absIconsDir, errBase := filepath.Abs(iconsDir)
	absFilePath, errFile := filepath.Abs(filePath)

	if errBase != nil || errFile != nil {
		http.Error(w, "Invalid path", http.StatusBadRequest)
		return
	}

	// Ensure the file path is within the icons directory
	if !strings.HasPrefix(absFilePath, absIconsDir+string(filepath.Separator)) && absFilePath != absIconsDir {
		http.Error(w, "Invalid path", http.StatusBadRequest)
		return
	}

	// Serve the file
	http.ServeFile(w, r, filePath)
}

// handleServeFavicon serves a cached favicon by link ID.
func (svc *Service) handleServeFavicon(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	if id == "" {
		http.Error(w, "invalid link id", http.StatusBadRequest)
		return
	}

	link, err := getLink(svc.dbPath, id)
	if err != nil {
		http.Error(w, "link not found", http.StatusNotFound)
		return
	}

	if link.FaviconPath == "" {
		http.Error(w, "no favicon", http.StatusNotFound)
		return
	}

	dataDir := svc.getDataDir()
	var faviconPath string

	// Check if it's a custom icon (starts with "icons/") or a fetched favicon
	if strings.HasPrefix(link.FaviconPath, "icons/") {
		faviconPath = filepath.Join(dataDir, link.FaviconPath)
	} else {
		faviconPath = filepath.Join(dataDir, "favicons", link.FaviconPath)
	}

	// Prevent directory traversal
	absPath, err := filepath.Abs(faviconPath)
	if err != nil {
		http.Error(w, "forbidden", http.StatusForbidden)
		return
	}

	expectedBase, _ := filepath.Abs(dataDir)
	if !strings.HasPrefix(absPath, expectedBase) {
		http.Error(w, "forbidden", http.StatusForbidden)
		return
	}

	// #nosec G703 - path is validated by filepath.Abs and HasPrefix check above
	if _, err := os.Stat(absPath); err != nil {
		http.Error(w, "not found", http.StatusNotFound)
		return
	}

	// Set appropriate content-type
	if strings.HasSuffix(absPath, ".svg") {
		w.Header().Set("Content-Type", "image/svg+xml")
	} else if strings.HasSuffix(absPath, ".png") {
		w.Header().Set("Content-Type", "image/png")
	} else if strings.HasSuffix(absPath, ".jpg") || strings.HasSuffix(absPath, ".jpeg") {
		w.Header().Set("Content-Type", "image/jpeg")
	} else if strings.HasSuffix(absPath, ".gif") {
		w.Header().Set("Content-Type", "image/gif")
	} else if strings.HasSuffix(absPath, ".webp") {
		w.Header().Set("Content-Type", "image/webp")
	} else {
		w.Header().Set("Content-Type", "image/x-icon")
	}

	http.ServeFile(w, r, absPath)
}

// getDataDir returns the data directory for this service.
func (svc *Service) getDataDir() string {
	os := svc.Deps.MustGetOsProvider()
	home, err := os.UserHomeDir()
	if err != nil {
		home = "."
	}
	return filepath.Join(home, ".keyop", "links")
}
