// Package idle monitors macOS user idle/active state and provides utilities
// for recording activity, persisting per-day summaries, and generating
// nightly idle reports.
//
// Overview
// The idle package uses macOS APIs to determine whether the local user is
// currently "active" or "idle" (based on a configurable threshold). On
// each periodic Check() the service emits a "status_update" message and
// associated metrics; these messages are used to derive per-host active
// periods and to generate daily reports.
//
// Configuration
// The service can be configured via the ServiceConfig.Config map. Supported
// configuration keys (all optional unless noted):
//
//   - threshold: string (duration)
//     The duration after which the user is considered idle, e.g. "5m".
//     If omitted or unparsable the default is 5m.
//
//   - idle_metric_name: string
//     The metric name used when emitting idle duration metrics. If omitted
//     a default of <service>.idle_duration is used.
//
//   - active_metric_name: string
//     The metric name used when emitting active duration metrics. If omitted
//     a default of <service>.active_duration is used.
//
//   - report_queue_file: string
//     Optional template path to a queue file containing serialized messages
//     for a given day. The template may include the token "yyyymmdd" which
//     will be replaced with a date in 20060102 format (for example:
//     "~/logs/keyop/queue.yyyymmdd.log"). If queue_file is not configured
//     nightly reports are skipped.
//
// Queue file format (events)
// For nightly reporting the package can read a queue file that contains one
// JSON message per line. Each line may be either a legacy core.Message JSON
// object or a core.Envelope (the code will attempt to unmarshal an Envelope
// first and fall back to a Message). Lines that cannot be parsed are
// ignored. Only messages with Event == "status_update" and timestamps that
// fall within the target day are considered when constructing reports.
//
// Example queue line (envelope style):
//
//	{"version":"1","id":"...","payload":{...}}
//
// Example legacy message line (simplified):
//
//	{"event":"status_update","hostname":"myhost","timestamp":"2023-10-31T09:01:12-07:00","status":"active"}
//
// Report generation
// Nightly reports are generated by maybeSendIdleReport and are intended to
// run once per day (the service attempts generation between 00:00 and 01:00
// local time for the previous calendar day). When generating a report the
// service will:
//   - determine the queue file path by replacing the token "yyyymmdd" in
//     the configured queue_file template with the previous day's date
//   - read the file and parse one JSON message per line
//   - collect all "status_update" messages for each host that fall within
//     the previous day
//   - construct per-host active periods by tracking transitions between
//     status values and aggregating contiguous active spans
//   - merge active periods across hosts to compute total active time and
//     create coverage intervals to calculate known vs unknown seconds
//   - compute totals (active, idle, unknown) and format a Markdown report
//     that is emitted as a core.Message with Event == "idle_report"
//
// Notes
//   - If report_queue_file is not configured nightly reports are skipped.
//   - Local YAML day-file support has been removed; report generation uses the events queue file when configured.
//
// Usage
// Initialize the service via NewService(deps, cfg) and provide the desired
// config keys described above. Register payloads with a core.PayloadRegistry
// using RegisterPayloads. The service's Check() method should be invoked on
// a periodic schedule by the host runtime (the package expects to run only
// on macOS/darwin).
package idle
