package cmd

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestRootCmd_Execute_with_No_Args(t *testing.T) {

	Execute()

	// this is a really weak assertion
	assert.True(t, true, "Execute() should not die with an error")

	// TODO: capture and check output, generated by cobra which logs to stdout
}
